// ─────────────────────────────────────────────────────────────────────────────
// projects.data.js — Reusable Project Data Model for Selected Works Facade
// ─────────────────────────────────────────────────────────────────────────────

export const PROJECTS_DATA = [
    {
        id: "narayana",
        slug: "narayana",
        number: "01",
        category: "HEALTHCARE · PRODUCT DESIGN",
        title: "Health Records 2.0",
        titleAccent: "2.0",
        description: "Making a patient’s health history easier to understand, track and act on.",
        company: "Narayana Health",
        contribution: "Research · UX Strategy · Product Design · UI · Design Systems",
        scale: "1M+ users",
        impact: "+30%* impact",
        isPlaceholderMetric: true,
        timeline: "2026 · 4 months",
        image: "sections/work/assets/narayana/cover.jpg",
        featured: true,
        caseStudyUrl: "projects/narayana.html",
        layoutVariant: "featured-left"
    },
    {
        id: "branchx",
        slug: "branchx",
        number: "02",
        category: "FINTECH · PRODUCT DESIGN",
        title: "Spend Categorisation",
        titleAccent: "Categorisation",
        description: "Making everyday spending easier to understand and manage.",
        company: "BranchX",
        contribution: "UX · UI · Interaction Design · Product Design",
        scale: "50K users",
        impact: "+10%* impact",
        isPlaceholderMetric: true,
        timeline: "2024 · 2 months",
        image: "sections/work/assets/branchx/cover.jpg",
        featured: true,
        caseStudyUrl: "projects/branchx.html",
        layoutVariant: "featured-right"
    },
    {
        id: "book-appointment",
        slug: "book-appointment",
        number: "03",
        category: "HEALTHCARE · PRODUCT DESIGN",
        title: "Book Appointment",
        titleAccent: "Appointment",
        description: "A simpler path from finding a doctor to booking an appointment.",
        company: "Narayana Health",
        contribution: "Product Design · UX · UI",
        scale: "National Rollout",
        impact: "+24% bookings*",
        isPlaceholderMetric: true,
        timeline: "2024 · 3 months",
        image: "sections/work/assets/book-appointment/cover.jpg",
        featured: false,
        gridSpan: "span-5",
        aspectRatio: "4 / 3",
        caseStudyUrl: "projects/book-appointment.html"
    },
    {
        id: "group-checkup",
        slug: "group-checkup",
        number: "04",
        category: "HEALTHCARE · PRODUCT DESIGN",
        title: "Group Health Checkup",
        titleAccent: "Checkup",
        description: "A group booking experience designed around families and shared healthcare needs.",
        company: "Narayana Health",
        contribution: "Product Design · UX · UI",
        scale: "Enterprise B2B2C",
        impact: "+15% bookings*",
        isPlaceholderMetric: true,
        timeline: "2024 · 3 months",
        image: "sections/work/assets/group-checkup/cover.jpg",
        featured: false,
        gridSpan: "span-7",
        aspectRatio: "16 / 9",
        caseStudyUrl: "projects/group-checkup.html"
    },
    {
        id: "dmrc",
        slug: "dmrc",
        number: "05",
        category: "MOBILITY · UI/UX",
        title: "Delhi Metro Companion",
        titleAccent: "Companion",
        description: "Finding a better route through Delhi’s metro network.",
        company: "Independent Case Study",
        contribution: "UX · UI · Interaction Design",
        scale: "2.6M Riders",
        impact: "+35% task success",
        isPlaceholderMetric: false,
        timeline: "2023 · 2 months",
        image: "sections/work/assets/dmrc/cover.png",
        featured: false,
        gridSpan: "span-4",
        aspectRatio: "1 / 1",
        caseStudyUrl: "projects/dmrc.html"
    },
    {
        id: "unishare",
        slug: "unishare",
        number: "06",
        category: "PRODUCT · UX/UI",
        title: "UniShare Platform",
        titleAccent: "Platform",
        description: "End-to-end ride-sharing experience for campus commuters.",
        company: "Campus Product",
        contribution: "UX · UI · Product Design",
        scale: "5K+ Students",
        impact: "-40% booking friction",
        isPlaceholderMetric: false,
        timeline: "2023 · 3 months",
        image: "sections/work/assets/unishare/cover.jpg",
        featured: false,
        gridSpan: "span-4",
        aspectRatio: "4 / 3",
        caseStudyUrl: "projects/unishare.html"
    },
    {
        id: "evy",
        slug: "evy",
        number: "07",
        category: "VUI · MULTIMODAL",
        title: "EVY In-Car Assistant",
        titleAccent: "In-Car Assistant",
        description: "A multimodal in-car experience combining voice assistance with visual interaction.",
        company: "Concept Design",
        contribution: "VUI · Interaction Design · Multimodal",
        scale: "Automotive HMI",
        impact: "Zero-gaze UI",
        isPlaceholderMetric: false,
        timeline: "2023 · 2 months",
        image: "sections/work/assets/evy/cover.jpg",
        featured: false,
        gridSpan: "span-4",
        aspectRatio: "4 / 3",
        caseStudyUrl: "projects/evy.html"
    }
];
